### ISSUE TITLE
DB Setup

### ISSUE THREAD

**Issue by Josecisneros001** [Josecisneros001/service-delivery#10]
Create DB.
Init DB according to:
https://app.diagrams.net/#G1LeUPBgrBrl4zXGoGHSZDB9qdyZUNaOwo
And according to:
https://documenter.getpostman.com/view/11507181/UUy4e6B7#e5e9aca6-6619-40cc-a7ad-6fb631c5cd68

**Comment by clarissavlsqz** [comment]
Tengo duda en especial con la tabla de services porque era la única que no tenía su propia id...checar si eso está correcto @Josecisneros001
