### ISSUE TITLE
UI Design

### ISSUE THREAD

**Issue by andrea-ramirez** [Josecisneros001/service-delivery#2]
**Desired Behavior**
- Create a frontend UI Design using Figma or a similar tool.
- Define all possible views and their interactions.

**Acceptance Criteria**
- [x] LogIn Design 
- [x] Home / Dashboard / Service Search 
- [x] Users Profile / Employees Profile

**Comment by Josecisneros001** [comment]
Moving this issue to next sprint.
Progress so far: 
https://www.figma.com/file/mMHLeyOoz9ub13v12hu98B/Service-Delivery?node-id=0%3A1
