### ISSUE TITLE
UML Design v1

### ISSUE THREAD

**Issue by andrea-ramirez** [Josecisneros001/service-delivery#5]
**Desired Behavior**
- Create UML Design using draw.io or any similar tool.
- Include UML Design in backend/db folder.

**Acceptance Criteria**
- [x] Structure defined.
- [x] Tables relation defined.

**Comment by Josecisneros001** [comment]
![image](https://user-images.githubusercontent.com/36351179/136143789-580dbd6a-86f7-48f1-8ca3-16dcb42bd2b2.png)
File:
https://drive.google.com/file/d/1LeUPBgrBrl4zXGoGHSZDB9qdyZUNaOwo/view?usp=sharing

**Comment by Josecisneros001** [comment]
Wiki entry: https://github.com/Josecisneros001/service-delivery/wiki/BACKEND
